args <- commandArgs(trailingOnly = TRUE)
identifier <- gsub(" *$", "", args[1])
numSimulations <- as.integer(args[2])
numSweeps <- as.integer(args[3])

L = scan(paste(identifier,"-histoActiveBanks.dat", sep=''))
matL=t(matrix(L,numSweeps,numSimulations))
resL=c()
for (i in c(1:numSweeps)) resL[i] = mean(matL[,i])
for (i in c(1:numSweeps)) resL[numSweeps+i] = sd(matL[,i])
for (i in c(1:numSweeps)) resL[2*numSweeps+i] = sd(matL[,i])
resL=matrix(resL,numSweeps,3)
write.table(resL ,paste(identifier,"-resActiveBanks.dat", sep=''), quote=FALSE , sep=" ")

L = scan(paste(identifier,"-histoL.dat", sep=''))
matL=t(matrix(L,numSweeps,numSimulations))
resL=c()
for (i in c(1:numSweeps)) resL[i] = mean(matL[,i])
for (i in c(1:numSweeps)) resL[numSweeps+i] = sd(matL[,i])
for (i in c(1:numSweeps)) resL[2*numSweeps+i] = sd(matL[,i])
resL=matrix(resL,numSweeps,3)
write.table(resL ,paste(identifier,"-resL.dat", sep=''), quote=FALSE , sep=" ")

L = scan(paste(identifier,"-histoLC.dat", sep=''))
matL=t(matrix(L,numSweeps,numSimulations))
resL=c()
for (i in c(1:numSweeps)) resL[i] = mean(matL[,i])
for (i in c(1:numSweeps)) resL[numSweeps+i] = sd(matL[,i])
for (i in c(1:numSweeps)) resL[2*numSweeps+i] = sd(matL[,i])
resL=matrix(resL,numSweeps,3)
write.table(resL ,paste(identifier,"-resLC.dat", sep='') , quote=FALSE , sep=" ")

L = scan(paste(identifier,"-histoI.dat", sep=''))
matL=t(matrix(L,numSweeps,numSimulations))
resL=c()
for (i in c(1:numSweeps)) resL[i] = mean(matL[,i])
for (i in c(1:numSweeps)) resL[numSweeps+i] = sd(matL[,i])
for (i in c(1:numSweeps)) resL[2*numSweeps+i] = sd(matL[,i])
resL=matrix(resL,numSweeps,3)
write.table(resL ,paste(identifier,"-resI.dat", sep=''), quote=FALSE , sep=" ")

L = scan(paste(identifier,"-histoD.dat", sep=''))
matL=t(matrix(L,numSweeps,numSimulations))
resL=c()
for (i in c(1:numSweeps)) resL[i] = mean(matL[,i])
for (i in c(1:numSweeps)) resL[numSweeps+i] = sd(matL[,i])
for (i in c(1:numSweeps)) resL[2*numSweeps+i] = sd(matL[,i])
resL=matrix(resL,numSweeps,3)
write.table(resL ,paste(identifier,"-resD.dat", sep=''), quote=FALSE , sep=" ")
